#!/usr/bin/env python3
# timeclient

import socket
import sys

def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <server_ip> <port>")
        sys.exit(1)

    server_ip = sys.argv[1]
    port = int(sys.argv[2])

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        try:
            sock.connect((server_ip, port))
            data = sock.recv(1024)
            if data:
                print(data.decode())
        except:
            pass

if __name__ == "__main__":
    main()
