#!/usr/bin/env python3

import os
import sys
import random
import time

def main():
    if len(sys.argv) < 2:
        os._exit(1)
    try:
        N = int(sys.argv[1])
        if not (120 <= N <= 180):
            os._exit(1)
    except:
        os._exit(1)

    operators = ['+', '-', '*', '/']
    for _ in range(N):
        X = random.randint(1,9)
        Y = random.randint(1,9)
        O = random.choice(operators)
        expression = f"{X} {O} {Y}\n"
        os.write(sys.stdout.fileno(), expression.encode())
        time.sleep(1)

    os._exit(0)

if __name__ == "__main__":
    main()
